#!/bin/sh

#SBATCH --job-name=ds003500-fmriprep
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds003500-fmriprep/.reproman/jobs/local/20221012-223029-a09a/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds003500-fmriprep/.reproman/jobs/local/20221012-223029-a09a/stderr

#SBATCH --nodes=10
#SBATCH --ntasks=38
#SBATCH --time=48:00:00
#SBATCH --partition=normal

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds003500-fmriprep/.reproman/jobs/local/20221012-223029-a09a

module load launcher
module load remora
module load ooops
set_io_param_batch $SLURM_JOBID 0 low
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 37); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

remora "$LAUNCHER_DIR"/paramrun